In [1]:
# libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
import pickle

In [2]:
data=pd.read_csv('car data.csv')
data.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [3]:
data=data.iloc[:,1:]
data.head()

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0  2014           3.35           5.59       27000    Petrol      Dealer   
1  2013           4.75           9.54       43000    Diesel      Dealer   
2  2017           7.25           9.85        6900    Petrol      Dealer   
3  2011           2.85           4.15        5200    Petrol      Dealer   
4  2014           4.60           6.87       42450    Diesel      Dealer   

  Transmission  Owner  
0       Manual      0  
1       Manual      0  
2       Manual      0  
3       Manual      0  
4       Manual      0

In [4]:
data['Currentyear']=2020

In [5]:
data.head()

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0  2014           3.35           5.59       27000    Petrol      Dealer   
1  2013           4.75           9.54       43000    Diesel      Dealer   
2  2017           7.25           9.85        6900    Petrol      Dealer   
3  2011           2.85           4.15        5200    Petrol      Dealer   
4  2014           4.60           6.87       42450    Diesel      Dealer   

  Transmission  Owner  Currentyear  
0       Manual      0         2020  
1       Manual      0         2020  
2       Manual      0         2020  
3       Manual      0         2020  
4       Manual      0         2020

In [6]:
data['no_year']=data['Currentyear']-data['Year']

In [7]:
data.head()

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0  2014           3.35           5.59       27000    Petrol      Dealer   
1  2013           4.75           9.54       43000    Diesel      Dealer   
2  2017           7.25           9.85        6900    Petrol      Dealer   
3  2011           2.85           4.15        5200    Petrol      Dealer   
4  2014           4.60           6.87       42450    Diesel      Dealer   

  Transmission  Owner  Currentyear  no_year  
0       Manual      0         2020        6  
1       Manual      0         2020        7  
2       Manual      0         2020        3  
3       Manual      0         2020        9  
4       Manual      0         2020        6

In [8]:
data.drop(['Year','Currentyear'],axis=1,inplace=True)

In [9]:
data.head()

Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0           3.35           5.59       27000    Petrol      Dealer   
1           4.75           9.54       43000    Diesel      Dealer   
2           7.25           9.85        6900    Petrol      Dealer   
3           2.85           4.15        5200    Petrol      Dealer   
4           4.60           6.87       42450    Diesel      Dealer   

  Transmission  Owner  no_year  
0       Manual      0        6  
1       Manual      0        7  
2       Manual      0        3  
3       Manual      0        9  
4       Manual      0        6

In [10]:
data=pd.get_dummies(data,drop_first=True)
data.head()

Selling_Price  Present_Price  Kms_Driven  Owner  no_year  Fuel_Type_Diesel  \
0           3.35           5.59       27000      0        6                 0   
1           4.75           9.54       43000      0        7                 1   
2           7.25           9.85        6900      0        3                 0   
3           2.85           4.15        5200      0        9                 0   
4           4.60           6.87       42450      0        6                 1   

   Fuel_Type_Petrol  Seller_Type_Individual  Transmission_Manual  
0                 1                       0                    1  
1                 0                       0                    1  
2                 1                       0                    1  
3                 1                       0                    1  
4                 0                       0                    1

In [11]:
y=data.iloc[:,:1]
y

Selling_Price
0             3.35
1             4.75
2             7.25
3             2.85
4             4.60
..             ...
296           9.50
297           4.00
298           3.35
299          11.50
300           5.30

[301 rows x 1 columns]

In [12]:
x=data.iloc[:,1:]
x

Present_Price  Kms_Driven  Owner  no_year  Fuel_Type_Diesel  \
0             5.59       27000      0        6                 0   
1             9.54       43000      0        7                 1   
2             9.85        6900      0        3                 0   
3             4.15        5200      0        9                 0   
4             6.87       42450      0        6                 1   
..             ...         ...    ...      ...               ...   
296          11.60       33988      0        4                 1   
297           5.90       60000      0        5                 0   
298          11.00       87934      0       11                 0   
299          12.50        9000      0        3                 1   
300           5.90        5464      0        4                 0   

     Fuel_Type_Petrol  Seller_Type_Individual  Transmission_Manual  
0                   1                       0                    1  
1                   0                       0                    1  
2                   1                       0                    1  
3                   1                       0                    1  
4                   0                       0                    1  
..                ...                     ...                  ...  
296                 0                       0                    1  
297                 1                       0                    1  
298                 1                       0                    1  
299                 0                       0                    1  
300                 1                       0                    1  

[301 rows x 8 columns]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42)

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lr=LinearRegression()

In [17]:
lr.fit(x_train,y_train)

LinearRegression()

In [18]:
y_pred=lr.predict(x_test)
y_pred

array([[ 2.88586938],
       [ 8.18824233],
       [ 6.43503523],
       [-1.57447783],
       [ 9.05504587],
       [ 7.42729023],
       [ 1.33421365],
       [ 0.81486481],
       [ 1.37165716],
       [ 7.4830155 ],
       [ 9.13175287],
       [ 0.56279917],
       [ 8.32720848],
       [ 3.35019639],
       [ 6.88307041],
       [ 3.10463218],
       [ 0.43131112],
       [10.70436354],
       [ 1.76766206],
       [ 2.34942156],
       [ 0.36284569],
       [ 8.12184715],
       [ 6.58504503],
       [ 2.65491321],
       [ 0.7693693 ],
       [ 3.70357739],
       [ 5.27138055],
       [ 2.83554678],
       [ 2.14898669],
       [ 1.75703047],
       [ 0.36533515],
       [ 9.10271188],
       [-0.72538233],
       [ 2.26461477],
       [ 8.5835019 ],
       [ 4.52609588],
       [ 7.21524545],
       [ 7.46886377],
       [ 2.94258376],
       [ 7.87095856],
       [ 3.84955018],
       [ 4.14006075],
       [ 4.35840513],
       [ 0.60090999],
       [ 7.34428852],
       [ 0

In [19]:
#prediction on user provide data

In [20]:
lr.predict([[5.59,24000,0,6,0,1,0,1]])

array([[3.9878554]])

In [31]:
result=lr.predict([[5.59,24000,0,6,0,1,0,1]])
result

array([[3.9878554]])

In [21]:
pickle.dump(lr,open('model.pkl','wb'))

model=pickle.load(open('model.pkl','rb'))